---
- name: Register number of cpu
  shell: cat /proc/cpuinfo |grep CPU|wc -l
  register: numCPU
- name: Reset latest configuration on join worker nodes
  shell: kubeadm reset --force
  tags: reset_worker
- name: Join worker nodes with 1 cpu
  shell: |
    kubeadm join "{{ control_plane_endpoint }}" --token "{{ hostvars['k8s_join']['token'] }}" \
    --discovery-token-ca-cert-hash sha256:"{{ hostvars['k8s_join']['hash'] }}" \
    --ignore-preflight-errors=NumCPU \
  when: numCPU.stdout == '1'
- name: Join worker node
  shell: |
    kubeadm join "{{ control_plane_endpoint }}" --token "{{ hostvars['k8s_join']['token'] }}" \
    --discovery-token-ca-cert-hash sha256:"{{ hostvars['k8s_join']['hash'] }}"
  when: numCPU.stdout > '1'
    