first_master: "192.168.0.50"
pod_network: "10.244.0.0/16"
control_plane_endpoint: "192.168.0.70:6443"
kubeadm_init_log_dir: "/var/log"
kubeadm_init_log: "kubeadm_init.log"
dashboard: "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml"
deploy_test_application: "no"
test_application_ns: "sock-shop"
manifest_dir: "/tmp"
nodelocaldns:
  domain: "cluster.local"
  localdns: "169.254.25.10"
interface_flannel: "eth1"